### PR TITLE
Changing license to Apache 2.0

### PR DESCRIPTION
**Pull request by tacosontitan**
This PR will effectively change the license to Apache 2.0.

### CODE REVIEW

**Comment by tacosontitan** [comment]
@Arkadiusz123 do you have any issue with this license change after your commit d71ca44fa941a9e71b1212c2d197ec4ebb21f491?

**Comment by tacosontitan** [comment]
@pizzamnchr do you have any issue with this license change after your commit 65ee6b098fae96f52e2df6fc603ac78bad3d8b4a?

**Comment by pizzamnchr** [comment]
All good with me :)

**Comment by tacosontitan** [comment]
Actually, we're going to stick with our current license. My apologies for the disturbance.

**Pull request closed without merging**
